### ISSUE TITLE
Missing reference to the Signalen oranization and its repos?

### ISSUE THREAD

**Issue by clausmullie** [Signalen/signalen.org#13]
I may have missed it, but if I'm not mistaken there is no reference/link to [this Signalen organization](https://github.com/Signalen) and the codebase repositories here. There is only a reference to this singalen.org repository. 

Perhaps this was done intentionally, but would it not make sense to signalen there is community activity in two places? Particularly as the reusability/configurability work is being done here?

**Comment by bvhme** [comment]
That would definitely make sense. It was not left out on purpose, this site just predates the other repositories in this organization and the choice to move them over here.

Proposed solution: add links to either the organization or the repositories to the website.

**Comment by felixfaassen** [comment]
new website includes link to organistation level repository
