### ISSUE TITLE
Website suggestion

### ISSUE THREAD

**Issue by vanbuiten** [Signalen/signalen.org#141]
@EdoPlantinga posted this issue in the Amsterdam/signals repository. Reposting it here because it relates to the signale.org website maintained by the VNG:

Congrats on the new website! Minor textual suggestion: the text block claim that Signalen is responsive, feels dated. Any service that isn't in the year 2022 should be ashamed. WCAG compliance ("Toegankelijk" is a better known term in NL), however, is still not standard, so I'd suggest to use that as the main feature (mentioning responsiveness as a sub feature if so desired).

Hth :-)

**Comment by jaccobrouwer** [comment]
Suggestions from Edo accepted and made the changes on Signalen.org
