### ISSUE TITLE
Both English and Dutch on the website

### ISSUE THREAD

**Issue by jaccobrouwer** [Signalen/signalen.org#16]

**Comment by Ainali** [comment]
I guess this was a misclick :)

**Comment by jaccobrouwer** [comment]
No it was not, there are three issues on the board, all referring to getting an UK version of Signalen.org available. As a matter of fact, there's so many issues on the board now, that I'm loosing sight of the actual work. So I propossed (email) that me and Alba are going to clean up the issue board

**Comment by felixfaassen** [comment]
solved by #41
