### ISSUE TITLE
Apply call for papers Common Ground Fieldlab

### ISSUE THREAD

**Issue by AlbaRoza** [Signalen/signalen.org#19]
Online Digital Government in Transition field lab taking place 5-7 October. Would be nice to apply for a talk there.
This is the [event page](https://commonground.nl/events/view/54477281/fieldlab-common-ground-14-tm-18-september).

- [ ] Reach out to Common Ground/VNG
- [ ] Prepare the proposal
- [ ] Prepare the talk/workshop, etc.

**Comment by felixfaassen** [comment]
event has passed
