### ISSUE TITLE
Become speakers at several meetups and conferences

### ISSUE THREAD

**Issue by AlbaRoza** [Signalen/signalen.org#22]
Get in touch with events such as:

- [ ] Data Amsterdam

- [ ] CodeForNL

- [ ] SCORE (Open to blogposts as well)

- [ ] DecidimFest 

Keep an eye on lists like: https://docs.google.com/spreadsheets/d/1CfAteon___U-wkrXSt5bxzRqBgjkVrVKxcZfHSatokU/edit#gid=2087359485

And so on and spread our word!

**Comment by Ainali** [comment]
Close for now.
