### ISSUE TITLE
Include Code of Conduct

### ISSUE THREAD

**Issue by AlbaRoza** [Signalen/signalen.org#28]
We could use the [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct/) template

**Comment by Ainali** [comment]
Or even better, how about the [scaled down version adapted by OpenZaak](https://github.com/open-zaak/open-zaak/blob/master/CODE_OF_CONDUCT.md)?

**Comment by Ainali** [comment]
Add the OpenZaak version, link from README, CONTRIBUTING and the contact page.

**Comment by AlbaRoza** [comment]
Solved in here: https://github.com/Signalen/signalen.org/pull/100
