### ISSUE TITLE
No links to other webpages from banner

### ISSUE THREAD

**Issue by ElenaFdR** [Signalen/signalen.org#4]
Navigation issue: it's hard to discover that there are other pages on this website.

**Comment by bvhme** [comment]
I agree some navigation would be a good idea.

But what is a banner?

**Comment by bvhme** [comment]
> A web banner or banner ad is a form of advertising on the World Wide Web delivered by an ad server. This form of online advertising entails embedding an advertisement into a web page. It is intended to attract traffic to a website by linking to the website of the advertiser.

— [Web banner, Wikipedia](https://en.wikipedia.org/wiki/Web_banner)

It seems to be not that. I'm guessing you see the solution in the header somewhere.

**Comment by bvhme** [comment]
All snark aside, I'll think of something. There are a few different avenues to take for implementation, they all make maintainance harder in different ways, so picking the right one is not an easy choice.
