### ISSUE TITLE
Work on the storytelling of the event

### ISSUE THREAD

**Issue by AlbaRoza** [Signalen/signalen.org#48]
- [x] Identify different development/implementation stages the community is on. The narrative of the event should follow the natural evolution, from starters to successful stories. (https://github.com/Signalen/signalen.org/issues/53)
- [x] Assign every municipality in the community to one of the phases.
- [x] Create an agenda
- [ ] Ask every municipality of the community to prepare a couple of slides explaining their current status.
- [ ] Short video made from existent one by Signalen.
- [ ] Prepare an introduction pitch of the current state of Signalen (Jacco)
- [ ] Prepare little video coverages pieces in between slots (Alba)
- [ ] Prepare to share a sneak peak or an exclusive content related to the Implementation guides (Arvid)
- [ ] Prepare a cool closing (Alba)
- [ ] Ask each participant to have a wishlist for this current year.
- [ ] Create spaces for Q&A (Breakout rooms?)

**Comment by AlbaRoza** [comment]
- [ ] Assign every municipality in the community to one of the phases.

**Comment by AlbaRoza** [comment]
Suggestion for agenda:

* Shorter video version as intro
* Overview of what Signalen is and what is the current status (pitch taskforce Jacco)
* Demo of Using Signalen (Jacco)
* Mini presentations (2 slides each) from other municipalities in different phases of using Signalen (challenges and lessons learned).
* 3 breakout rooms with Q&A from new municipalities
* VNG + Foundation for Public Code: what can we do to help your municipality?

**Comment by bvhme** [comment]
Looks great @AlbaRoza, let me know if I can help with anything.

**Comment by jaccobrouwer** [comment]
![image](https://user-images.githubusercontent.com/63238094/108355607-560edd00-71eb-11eb-9233-42faa90daa7b.png)
