### ISSUE TITLE
Create a Comms. campaign

### ISSUE THREAD

**Issue by AlbaRoza** [Signalen/signalen.org#49]
- [x] Communicate in newsletter of Signalen
- [x] Publish a banner in website Signalen.org
- [ ] Create a trailer movie for the "pre" phase/reuse pieces of the existing video.
- [ ] Create a movie to be presented during the event (coffee break type of thing)
- [x] Structure the different phases: pre, during, after with its actors and objectives.
- [x] Promotion: reach out to meetups (DataLab Amsterdam), Pleio, BZN newsletter, Foundation for Public Code, etc.
- [x] Coordinate with CommonGround comms. team. Specially after Fieldlab!
- [x] Post it in Signalen's blog/news section (WIP)

**Comment by Ainali** [comment]
This was for the second  community day.
