### ISSUE TITLE
Add known Signalen vendors to contact page

### ISSUE THREAD

**Issue by felixfaassen** [Signalen/signalen.org#59]
We should make a list of vendors who are either involved in:

- Hosting Signalen
- Doing implementation support for Signalen
- Actively develop on Signalen

Rational is for new Signalen users to see there are vendors with experience about Signalen.

**Comment by jaccobrouwer** [comment]
MACOIN (Arvid and Jelle)
Beheervisie (Melddesk) (Jan Peter Reumerman)
TRUE (service provider) (Daniel)
Maykin Media (Joeri)
TiltShift (Johan, Joris of Maarten)
