### ISSUE TITLE
Provide information about meeting schedule and links to meetings

### ISSUE THREAD

**Issue by felixfaassen** [Signalen/signalen.org#60]
We should provide information about the meeting schedules and links to meetings on the Signalen website to be more open and welcome contributions. Also, provide pointers so people can learn how they can join these calls.

**Comment by Ainali** [comment]
A good place to put it would be either in the CONTRIBUTING file or, perhaps even better, to create a new GOVERNANCE file where the scope of these meetings could be explained in more detail.
