### ISSUE TITLE
Add news post on all reccuring meetings that are open

### ISSUE THREAD

**Issue by Ainali** [Signalen/signalen.org#95]
There are a few meetings that are open to anyone interested, but it might be hard to find them. We should at least have a news post talking about them and what they usually contain.

- [ ] Dutch version
   - [ ] Frontmatter so it gets picked up on the listing page 
- [ ] English version
   - [ ] Frontmatter so it gets picked up on the listing page

**Comment by Ainali** [comment]
These are the meetings I am sure of: 

- Product steering, third Thirsday of the month 9:00-10:00 UTC, https://meet.publiccode.net/SignalenProductSteering
- Developer meeting, Thursdays 11:00-12:00 UTC, https://meet.jit.si/SignalenDevAmsVNG

Then we might also have: 

- Community update, every second Thursday 8:15-9:00 UTC 

But I am unsure if the last one has right schedule and where the meeting is taking place.

**Comment by AlbaRoza** [comment]
Is there an option of adding some sort of plugin to the main website with that information? i think that would be useful, although don't know how accessible...

**Comment by Ainali** [comment]
A real calendar would be good, but is probably a bit of a larger work too get done if I understood @felixfaassen right. Either way, an announcing blog post might be good to be able to point people to that might be interested in joining (for example civil servants outside of the Netherlands that are evaluating Signalen).

**Comment by Ainali** [comment]
Ping @jaccobrouwer: what is the schedule for the Community update and which link should I use?

**Comment by Ainali** [comment]
It's already published on https://signalen.org/en/contact/
Update with times and make it easier to add the dev meeting
